version: '3'

services:
  database:
    image: postgres:latest
    restart: always
    container_name: DB_CODE_PIX
    tty: true
    volumes:
      - ./database/postgres:/data/postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'